services:
  cadastrocliente.application:
    image: ${DOCKER_REGISTRY-}cadastroclienteapplication
    build: 
      context: .
      dockerfile: src/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=CadastroClienteDB;User Id=sa;Password=CadCliente@1234;TrustServerCertificate=true;Encrypt=False;Integrated Security=False;
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: 'sqlserver'
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "CadCliente@1234"
    ports:
      - '11433:1433'
    expose:
      - 1433
    volumes:
      - volume-banco:/var/opt/mssql
  frontend:
    container_name: frontend
    build:
      context: src/cadastro-cliente-app
    ports:
      - 4200:4200
    volumes:
      - ./angular:/project
      - /project/node_modules
    depends_on:
      - cadastrocliente.application
      
volumes:
  volume-banco: